server:
  port: 6969

#Spring properties
spring:
  application:
    name: accounts

build:
  version: "3.0"

accounts:
  message: "Welcome to banking app from section 6"
  contactDetails:
    name: "Vishal Tuniki"
    email: "{cipher}4ed767f7b00565854888e7c6c31f0d3c33ade232326b7d0ece1d321d57b7802a"
  onCallSupport:
    - 1234567890
    - 9876543210